Add best practice
fleetdm/fleet-mdm-gitops pull request #11
Opened 2023-08-31 13:40 UTC by noahtalerman

The `best-pratice/` folder now includes an example for the best practice when using Fleet and GitOps. This was discussed during MDM design review on 2023-08-29.

Still TODO after this PR is merged:

- Update the GitHub action to support this story: As a Fleet user, I want to clone the file structure, make a change to any file, and have this reflected in my Fleet so that I can use GitOps to manage Fleet. 
  - Noah: I added this to feature fest (2023-08-31)

2023-08-31 13:45 UTC, noahtalerman commented
@lukeheath during design review (MDM) we decided on a best practice for using Fleet with GitOps.

This PR adds a template folder structure for the best practice. 

Soon, we'll update the GitHub action to support this template. Later, we'll update the template to instead use dogfood's queries, policies, controls, and settings. We can use this repo to dogfood the GitHub action.

cc @zhumo @rachaelshaw @mikermcneil

2023-09-01 15:20 UTC, lukeheath requested changes
Nice! Just a couple missing periods.

2023-09-01 15:20 UTC, lukeheath commented on best-practice/README.md
> +  - `<team name>` - folder for each team, with team-specific configs
Nit: missing period at the end of the sentence for consistency.

2023-09-01 15:20 UTC, lukeheath commented on best-practice/README.md
> +    - `<team name>.controls.yml` - controls config for a specific team, including configuration profiles, OS updates, setup experience, and scripts
```suggestion
    - `<team name>.controls.yml` - controls config for a specific team, including configuration profiles, OS updates, setup experience, and scripts.
```

2023-09-01 15:20 UTC, lukeheath commented on best-practice/README.md
> +  - `<team name>` - folder for each team, with team-specific configs
```suggestion
- `teams` - folder for teams in Fleet. These folders contain team-level policies, queries, controls, and settings.
  - `<team name>` - folder for each team, with team-specific configs.
```

2023-09-01 21:06 UTC, noahtalerman commented
Thanks Luke!

2023-09-05 14:42 UTC, lukeheath approved these changes

2023-09-05 16:01 UTC, noahtalerman commented
@lukeheath can you please grant me write access to this repo? I can't merge the approved PR.

Maybe everyone at Fleet should have write access?

2023-09-05 19:58 UTC, merged

2023-09-05 19:58 UTC, noahtalerman commented
@lukeheath yep! Merged. Thanks